### ISSUE TITLE
Example with with_state and nested router?

### ISSUE THREAD

**Issue by hongquan** [Atrociously/axum-named-routes#2]
Could you provide an example with `with_state` and `nest`?

**Comment by Atrociously** [comment]
Hi sorry I haven't responded, this router should work the same as the standard axum router [with_state](https://docs.rs/axum/latest/axum/struct.Router.html#method.with_state) function. If you get errors I would love to see some example code.

**Comment by hongquan** [comment]
Thank you. I reverted back to pure `Router`.
